spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner_matching_db?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # redis
  redis:
    port: 6379
    host: localhost
    database: 0
  session:
    timeout: 86400
    store-type: redis
#  config:
#    activate:
#      on-profile: dev
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
#  production: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.cola.partnermatching.controller
